# Goreleaser documentation can be found at http://goreleaser.com
before:
  hooks:
    - go mod download
    - go generate ./...
    - git diff
builds:
  - id: linux-build
    ldflags:
      - -extldflags=-static
    env:
      - CGO_ENABLED=1
    goos:
      - linux
    goarch:
      - amd64
      - arm64
  - id: darwin-build
    ldflags:
      - -s
    env:
      - CGO_ENABLED=1
      - CC=/home/runner/work/osxcross/target/bin/o64-clang
      - CXX=/home/runner/work/osxcross/target/bin/o64-clang++
    goos:
      - darwin
    goarch:
      - amd64
      - arm64
archives:
  - replacements:
      darwin: Mac
      linux: Linux
      386: 32-bit
      amd64: 64-bit
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'