name: goreleaser

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write
  # packages: write
  # issues: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16
        id: go

      - name: Install dependencies
        run: |
          go get -v -t -d ./...
      - name: Run build
        run: |
          go build -o network-validator-tools
      - name: Prepare tag name
        uses: olegtarasov/get-tag@v2.1
        id: tagName

      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          name: ${{ steps.tagName.outputs.tag }}
          draft: false
          files: |
            ./network-validator-tools*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}